### ISSUE TITLE
update tar archive to contain 18.0.2

### ISSUE THREAD

**Issue by jxsl13** [bitnami/bitnami-docker-keycloak-config-cli#4]
### Name and Version

bitnami/keycloak-config-cli:5.2.1-debian-11-r2

### What is the problem this feature will solve?

I'm trying to us ethe bitnami/keylcoak helm chart to deploy a keycloak with a prefedined realm for integration testing.
Seemingly the chart is already expecting keycloak 18.0.2 while using this docker image for the keycloak configuration process which only has the version 18.0.1

https://downloads.bitnami.com/files/stacksmith/keycloak-config-cli-5.2.1-0-linux-amd64-debian-11.tar.gz

### What is the feature you are proposing to solve the problem?

Update the tar archive to also contain a client for 18.0.2

### What alternatives have you considered?

I'm downgrading the keycloak version to 18.0.1

**Comment by marcosbc** [comment]
Hi @jxsl13, unfortunately there hasn't been a new version for keycloak-config-cli with the new versions yet. You can view the list of available versions here: https://github.com/adorsys/keycloak-config-cli/releases
